export const Users = [
  {
    id: 1,
    profilePicture: "user/1.jpg",
    username: "Sam Holland",
  },
  {
    id: 2,
    profilePicture: "user/2.jpg",
    username: "Peggy Carter",
  },
  {
    id: 3,
    profilePicture: "user/3.jpg",
    username: "Alex Evans",
  },
  {
    id: 4,
    profilePicture: "user/4.jpg",
    username: "James Topley",
  },
  {
    id: 5,
    profilePicture: "user/5.jpg",
    username: "Alina Olsen",
  },
  {
    id: 6,
    profilePicture: "user/6.jpg",
    username: "Gal Gadot",
  },
  {
    id: 7,
    profilePicture: "user/7.jpg",
    username: "Travis Blake",
  },
  {
    id: 8,
    profilePicture: "user/8.jpg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "user/9.jpg",
    username: "Kamala Khan",
  },
  {
    id: 10,
    profilePicture: "user/10.jpg",
    username: "Sruti Samuel",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/p1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/p2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/p3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/p4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/p5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/p6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/p7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/p8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/p9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/p10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
